-- Fix documents table embedding column type
-- Convert from jsonb/text to vector(768)

-- Drop existing column if it's not the right type
DO $$ 
BEGIN
  -- Check if column exists and is not vector type
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'documents' 
    AND column_name = 'embedding'
    AND data_type != 'USER-DEFINED'
  ) THEN
    -- Drop the column
    ALTER TABLE documents DROP COLUMN IF EXISTS embedding;
    
    -- Recreate with correct type
    ALTER TABLE documents ADD COLUMN embedding vector(768);
    
    RAISE NOTICE 'Embedding column converted to vector(768)';
  ELSIF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'documents' 
    AND column_name = 'embedding'
  ) THEN
    -- Column doesn't exist, create it
    ALTER TABLE documents ADD COLUMN embedding vector(768);
    
    RAISE NOTICE 'Embedding column created as vector(768)';
  ELSE
    RAISE NOTICE 'Embedding column already correct type';
  END IF;
END $$;

-- Add index for vector similarity search if not exists
CREATE INDEX IF NOT EXISTS documents_embedding_idx 
ON documents 
USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

-- Add comment
COMMENT ON COLUMN documents.embedding IS 'Vector embedding (768 dimensions) generated by Gemini gemini-embedding-001';
