import fs from "node:fs";
import path from "node:path";

// design.md D9 / responsive-images spec "TPV Figure Ships Responsive
// Srcset": TpvModuleFigure renders a multi-width srcset (generated by
// generateResponsiveImage() at build/asset-generation time) + sizes only
// for the standard 936x702 figure. Compras/FoodCost at 900x675 are
// explicitly out of scope (design.md D9) and must render unchanged — no
// srcset at all. No jest-environment-jsdom in this repo (see
// tests/unit/tpvModuleFigures.structure.test.ts), so this is a source-text
// check of the component, same convention as that file.
const SRC = path.resolve(__dirname, "../../src");
const FIGURE_PATH = path.join(
  SRC,
  "shared/components/tpv/TpvModuleFigure.tsx",
);
const readSource = () => fs.readFileSync(FIGURE_PATH, "utf-8");

describe("TpvModuleFigure responsive srcset (design.md D9, responsive-images spec)", () => {
  it("exports TPV_RESPONSIVE_WIDTHS = [480, 720, 936]", () => {
    const source = readSource();
    expect(source).toMatch(
      /export const TPV_RESPONSIVE_WIDTHS\s*=\s*\[\s*480\s*,\s*720\s*,\s*936\s*\]/,
    );
  });

  it("renders srcset/sizes on the <img> only when width===936", () => {
    const source = readSource();
    expect(source).toMatch(/width\s*===\s*936/);
    expect(source).toMatch(/srcSet=\{/);
    expect(source).toMatch(/sizes=\{/);
    expect(source).toMatch(
      /"\(min-width: 1024px\) 556px, calc\(100vw - 2rem\)"/,
    );
  });

  it("builds each non-original srcset entry as `{base}-{w}w.webp {w}w`, matching generateResponsiveImage()'s output filenames", () => {
    const source = readSource();
    expect(source).toMatch(/-\$\{w(idth)?\}w\.webp/);
  });
});
